"""create todolists table and todos table

Revision ID: 58da2791085f
Revises: 05bc57ecb7d4
Create Date: 2021-09-21 16:30:46.164178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da2791085f'
down_revision = '05bc57ecb7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('xPos', sa.Integer(), nullable=False),
    sa.Column('yPos', sa.Integer(), nullable=False),
    sa.Column('boardId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('todoListId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['todoListId'], ['todo_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
