"""update boaruser table

Revision ID: 7d39251b2381
Revises: 40549430f0f5
Create Date: 2021-09-29 09:23:50.670257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d39251b2381'
down_revision = '40549430f0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_users', sa.Column('owner', sa.Boolean(), nullable=True))
    op.add_column('board_users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_users', 'verified')
    op.drop_column('board_users', 'owner')
    # ### end Alembic commands ###
