"""create boards table

Revision ID: 24677aedab74
Revises: ffdc0a98111c
Create Date: 2021-09-21 12:06:21.079219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24677aedab74'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('backgroundUrl', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    # ### end Alembic commands ###
