"""added sticky notes table

Revision ID: 40549430f0f5
Revises: 58da2791085f
Create Date: 2021-09-28 08:23:09.484625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40549430f0f5'
down_revision = '58da2791085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticky_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('xPos', sa.Integer(), nullable=False),
    sa.Column('yPos', sa.Integer(), nullable=False),
    sa.Column('boardId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticky_notes')
    # ### end Alembic commands ###
